### ISSUE TITLE
Add start and stop commands

### ISSUE THREAD

**Issue by alambike** [prefapp/puzzle#16]
It will be very useful enable the same options as docker-compose to **start** and **stop**  services and containers

**Comment by frmadem** [comment]
A start and stop of the entire service has been implemented. 

https://github.com/prefapp/puzzle/tree/start_stop

But the start and stop over individual containers is not fully implemented yet.

**Comment by frmadem** [comment]
The start of a individual container doesn't seem possible in the sense that is has no meaning without its compose. 

The stop of specific containers within a service could be implemented but there is the problem of how to find out their names

**Comment by frmadem** [comment]
It seems also that we need a method to know if the service is built or not. It the service is not built the execution of start/stop is meaningless since there is no containers to operate.

**Comment by alambike** [comment]
Why not pass the responsability to docker-compose, and let it make the checks and send the warnings that considers.

**Comment by alambike** [comment]
https://github.com/prefapp/puzzle/pull/37
