### ISSUE TITLE
Service down must not be deleted

### ISSUE THREAD

**Issue by frmadem** [prefapp/puzzle#22]
When puzzle executes 'down' on a service in a compilation, the service must be stopped but the service folder must not be deleted

**Comment by frmadem** [comment]
A new behaviour for 'down' command has been established:

puzzle down service1 ... serviceN 

performs a down of the service/s but, it does not delete their configuration. 

puzzle down service1...serviceN  --destroy 

Does the same but destroys services' configurations and, if there is no service left, the compilation is erased too.

**Comment by alambike** [comment]
Now compilation directories are never dropped:

```
puzzle up panel gpac constructor arquitecto promotor
```
```puzzle down```
```bash
ls -l puzzle_compilation/
total 128
drwxrwxr-x 2 alambike alambike   4096 ago 29 19:48 arquitecto
drwxrwxr-x 2 alambike alambike   4096 ago 29 19:48 gpac
drwxrwxr-x 2 alambike alambike   4096 ago 29 19:48 panel
drwxrwxr-x 2 alambike alambike   4096 ago 29 19:48 promotor
-rw-rw-r-- 1 alambike alambike 113206 ago 29 19:48 puzzle.db
```

And we have to delete compilation directory manually so puzzle can create a new environment.

**Comment by alambike** [comment]
I need to use new  **--destroy** flag
