### ISSUE TITLE
Command to list tasks 

### ISSUE THREAD

**Issue by alambike** [prefapp/puzzle#26]
If you have not access to piece definition, would be very useful to have a command to list all construction's tasks, something like

**puzzle tasklist __piece__**

Or maybe just a show command that dumps directly all piece information.

**Comment by frmadem** [comment]
Solved in https://github.com/prefapp/puzzle/commit/0198ea36e7dfa324a1f91082c9bb8791c5b4b964, 

```bash
puzzle task <service>
```

Prints a list of available task for the service <service> defined in the piece
