### ISSUE TITLE
Poder pasar a "puzzle generate piece" la ruta del box y el nombre de la pieza

### ISSUE THREAD

**Issue by alambike** [prefapp/puzzle#31]
"puzzle generate piece" agregarialle 2 parametros (opcionais), donde digas a box onde queres  y nome da peza

> puzzle generate piece dev_box mi_app.yml

**Comment by frmadem** [comment]
Solved in https://github.com/prefapp/puzzle/commit/c59ad51df585ef44999647a8a4a7e87c446e9075
